mysql:
  host: 116.196.110.205
  port: 3366
  config: charset=utf8&parseTime=true&loc=Local
  db: zr
  user: zr
  password: 123456
  log_level: dev
logger:
  level: info
  prefix: '[zr]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 7456
  env: release
site_info:
  create_at: "2024-06-20"
  icp: 蜀ICP备
  title: 朝而往
  qq_image: ""
  version: 0.0.0
  email: 2229064648@qq.com
  wechat: ""
  name: 朝而往
  job: 学生
  addr: 安徽合肥
  slogan: 朝而往
  slogan_en: ZHAOERWANG
  web: ""
  bilibili: ""
  github: ""
  gitee: ""
jwt:
  secret: xxxxx
  expires: 48
  issuer: zr
email:
  host: smtp.qq.com
  port: 465
  user: 1111112@qq.com
  password: ""
  default_from_email: zr
  user_ssl: false
  user_tls: false
qq:
  app_id: xxx
  key: xxx
  redirect: https://xx.xx.com/login?flag=qq
qiniu:
  enable: false
  access_key: xxx
  secret_key: xxx
  bucket: xxx
  cdn: http://xxx.xxx.com
  zone: xxx
  size: 10
redis:
  ip: 127.0.0.1
  port: 6379
  password: xxxxx
  pool_size: 100
upload:
  size: 10
  path: uploads/files
  suffix:
  - jpg
  - jpeg
  - bmp
  - tiff
  - png
  - gif
  - webp
  - svg
  - pdf
  - csv
  - xls
  - xlsx
